import PDFDocument from 'pdfkit';
import geminiClient from './geminiClient.js';

const pdfGenerator = async (answers) => {
  // Translate all answers to English using Gemini
  const translatedAnswers = [];
  for (let i = 0; i < answers.length; i++) {
    if (answers[i]) {
      try {
        const english = await geminiClient.translateToEnglish(answers[i]);
        translatedAnswers[i] = english;
      } catch (e) {
        translatedAnswers[i] = answers[i];
      }
    } else {
      translatedAnswers[i] = '';
    }
  }

  return new Promise((resolve) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    });

    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    // Header
    doc.fontSize(16)
       .font('Helvetica-Bold')
       .text('RESUME', { align: 'center' })
       .font('Helvetica')
       .text(`${translatedAnswers[0] || 'Name'} | ${translatedAnswers[1] || 'Profession'}`)
       doc.fontSize(11)
       .font('Helvetica')
       .text(`Address: ${translatedAnswers[6] || 'Address'}`)
       .font('Helvetica')
       .text(`Phone: ${translatedAnswers[7] || 'Phone'}`);
    doc.moveDown(2);

    // Professional Summary
    doc.fontSize(14)
       .font('Helvetica-Bold')
       .text('PROFESSIONAL SUMMARY');
    doc.moveDown(0.5);
    doc.fontSize(11)
       .font('Helvetica')
       .text(`${translatedAnswers[1] || 'Profession'} with experience in the field.`);
    doc.moveDown(1);

    // Education
    doc.fontSize(14)
       .font('Helvetica-Bold')
       .text('EDUCATION');
    doc.moveDown(0.5);
    doc.fontSize(11)
       .font('Helvetica')
       .text(translatedAnswers[2] || 'Education');
    doc.moveDown(1);

    // Skills
    doc.fontSize(14)
       .font('Helvetica-Bold')
       .text('SKILLS');
    doc.moveDown(0.5);
    doc.fontSize(11)
       .font('Helvetica')
       .text(translatedAnswers[3] || 'Skills');
    doc.moveDown(1);

    // Experience
    doc.fontSize(14)
       .font('Helvetica-Bold')
       .text('EXPERIENCE');
    doc.moveDown(0.5);
    doc.fontSize(11)
       .font('Helvetica')
       .text(translatedAnswers[4] || 'Experience');
    doc.moveDown(1);

    // Certifications
    doc.fontSize(14)
       .font('Helvetica-Bold')
       .text('CERTIFICATIONS');
    doc.moveDown(0.5);
    doc.fontSize(11)
       .font('Helvetica')
       .text(translatedAnswers[5] || 'No certifications');
    doc.moveDown(1);

    doc.moveDown(2);
    doc.fontSize(10)
       .font('Helvetica-Oblique')
       .text('This resume was generated by AsaanCV', { align: 'center' });

    doc.end();
  });
};

export default pdfGenerator;
