import PDFDocument from 'pdfkit';

// Enhanced Urdu to English translation mapping
const urduToEnglish = {
  // Common names
  'محمد': 'Muhammad',
  'علی': 'Ali',
  'احمد': 'Ahmed',
  'عمر': 'Umar',
  'فاطمہ': 'Fatima',
  'عائشہ': 'Aisha',
  'حسن': 'Hassan',
  'حسین': 'Hussain',
  'عبداللہ': 'Abdullah',
  'عبدالرحمن': 'Abdur Rahman',
  'عبدالرزاق': 'Abdur Razzaq',
  'عبدالستار': 'Abdus Sattar',
  'عبدالغفار': 'Abdul Ghaffar',
  'عبدالقیوم': 'Abdul Qayyum',
  'عبدالوحید': 'Abdul Waheed',
  
  // Education terms
  'میٹرک': 'Matric',
  'انٹر': 'Intermediate',
  'بی اے': 'BA',
  'بی ایس': 'BS',
  'بی کام': 'B.Com',
  'بی ایڈ': 'B.Ed',
  'ماسٹر': 'Masters',
  'ایم اے': 'MA',
  'ایم ایس': 'MS',
  'پی ایچ ڈی': 'PhD',
  'ڈگری': 'Degree',
  'ڈپلومہ': 'Diploma',
  'سرٹیفکیٹ': 'Certificate',
  'تعلیم': 'Education',
  'اسکول': 'School',
  'کالج': 'College',
  'یونیورسٹی': 'University',
  
  // Skills terms
  'الیکٹریشن': 'Electrician',
  'پلمبر': 'Plumber',
  'مکینک': 'Mechanic',
  'ڈرائیور': 'Driver',
  'کنسٹرکشن': 'Construction',
  'پینٹر': 'Painter',
  'کارپینٹر': 'Carpenter',
  'ویلڈر': 'Welder',
  'ماسن': 'Mason',
  'لوہار': 'Blacksmith',
  'ٹیلر': 'Tailor',
  'کک': 'Cook',
  'گارڈ': 'Guard',
  'سیکیورٹی': 'Security',
  'کلیینر': 'Cleaner',
  'لیبر': 'Labor',
  'ہیلپر': 'Helper',
  'اسسٹنٹ': 'Assistant',
  'سوپروائزر': 'Supervisor',
  'فورمین': 'Foreman',
  
  // Experience terms
  'سال': 'years',
  'ماہ': 'months',
  'دن': 'days',
  'تجربہ': 'experience',
  'کام': 'work',
  'نوکری': 'job',
  'کمپنی': 'company',
  'فیکٹری': 'factory',
  'دکان': 'shop',
  'گھر': 'house',
  'دفتر': 'office',
  'پلانٹ': 'plant',
  'ورکشاپ': 'workshop',
  'سائٹ': 'site',
  'پروجیکٹ': 'project',
  'فری لانس': 'Freelance',
  'پارٹ ٹائم': 'Part-time',
  'فل ٹائم': 'Full-time',
  
  // Contact terms
  'فون': 'phone',
  'رابطہ': 'contact',
  'نمبر': 'number',
  'موبائل': 'mobile',
  'ٹیلیفون': 'telephone',
  
  // Common words
  'ہوں': 'am',
  'ہیں': 'are',
  'ہے': 'is',
  'کا': 'of',
  'کی': 'of',
  'کے': 'of',
  'میں': 'in',
  'پر': 'on',
  'سے': 'from',
  'تک': 'until',
  'کے ساتھ': 'with',
  'کے لیے': 'for',
  'کے بارے میں': 'about',
  'کے مطابق': 'according to',
  'کے علاوہ': 'except',
  'کے بعد': 'after',
  'کے پہلے': 'before',
  'کے اوپر': 'above',
  'کے نیچے': 'below',
  'کے اندر': 'inside',
  'کے باہر': 'outside'
};

// Function to translate Urdu text to English
const translateToEnglish = (text) => {
  if (!text) return '';
  
  let translated = text;
  
  // Replace Urdu words with English equivalents
  Object.keys(urduToEnglish).forEach(urduWord => {
    const englishWord = urduToEnglish[urduWord];
    const regex = new RegExp(urduWord, 'gi');
    translated = translated.replace(regex, englishWord);
  });
  
  // Clean up common patterns
  translated = translated
    .replace(/\s+/g, ' ') // Remove extra spaces
    .replace(/^\s+|\s+$/g, '') // Trim
    .replace(/\s+([.,!?])/g, '$1') // Remove spaces before punctuation
    .replace(/([.,!?])\s+/g, '$1 ') // Add space after punctuation
    .replace(/\s+/g, ' ') // Final space cleanup
    .trim();
  
  return translated || text; // Return original if no translation found
};

const pdfGenerator = async (answers) => {
  return new Promise((resolve) => {
    const doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    });

    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));

    // Header
    doc.fontSize(24)
       .font('Helvetica-Bold')
       .text('RESUME', { align: 'center' });
    
    doc.moveDown(0.5);
    doc.fontSize(12)
       .font('Helvetica')
       .text('Generated by AsaanCV', { align: 'center' });
    
    doc.moveDown(2);

    // Personal Information
    if (answers[0]) {
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('PERSONAL INFORMATION');
      
      doc.moveDown(0.5);
      doc.fontSize(12)
         .font('Helvetica')
         .text(`Name: ${translateToEnglish(answers[0])}`);
      
      doc.moveDown(1);
    }

    // Education
    if (answers[1]) {
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('EDUCATION');
      
      doc.moveDown(0.5);
      doc.fontSize(12)
         .font('Helvetica')
         .text(translateToEnglish(answers[1]));
      
      doc.moveDown(1);
    }

    // Skills
    if (answers[2]) {
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('SKILLS');
      
      doc.moveDown(0.5);
      doc.fontSize(12)
         .font('Helvetica')
         .text(translateToEnglish(answers[2]));
      
      doc.moveDown(1);
    }

    // Experience
    if (answers[3]) {
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('EXPERIENCE');
      
      doc.moveDown(0.5);
      doc.fontSize(12)
         .font('Helvetica')
         .text(translateToEnglish(answers[3]));
      
      doc.moveDown(1);
    }

    // Contact
    if (answers[4]) {
      doc.fontSize(16)
         .font('Helvetica-Bold')
         .text('CONTACT');
      
      doc.moveDown(0.5);
      doc.fontSize(12)
         .font('Helvetica')
         .text(`Phone: ${answers[4]}`);
      
      doc.moveDown(1);
    }

    // Footer
    doc.moveDown(2);
    doc.fontSize(10)
       .font('Helvetica')
       .text('This resume was generated by AsaanCV', { align: 'center' });

    doc.end();
  });
};

export default pdfGenerator;
